FROM cycoresystems/rtpproxy:latest

EXPOSE 7722 10000-11000 2223
# CMD ["rtpproxy", "-l","10.6.6.5", "-s", "udp:127.0.0.1:7722","-u","rtpproxy:rtpproxy"]
#CMD ["rtppengine", "-l","10.6.6.5", "-s", "udp:127.0.0.1:2223","-u","rtppengine:rtppengine"]